name: pubtest_example_simple
dependencies:
  pubtest_example_simple_dependency:
    path: ../simple_dependency
dev_dependencies:
  test: '>=0.12.24'
  dev_test: any
  pubtest:
    git: git://github.com/tekartik/pubtest.dart

