name: pubtest_example_simple
dependencies:
  pubtest_example_simple_dependency:
    path: ../simple_dependency
dev_dependencies:
  test: '>=1.2.0'
  dev_test: '>=0.12.0-dev.1'
  pubtest:
    git:
      url: git://github.com/tekartik/pubtest.dart
      ref: dart2

