name: pubtest_example_simple
publish_to: none
environment:
  sdk: ^3.7.0
dependencies:
  pubtest_example_simple_dependency:
    path: ../simple_dependency
dev_dependencies:
  test: '>=1.2.0'
  dev_build: '>=0.12.0-dev.1'
  lints:
