name: pubtest_example_simple_dependency
environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'
dev_dependencies:
  test: '>=1.2.0'
  pubtest:
    git:
      url: git://github.com/tekartik/pubtest.dart
      ref: dart2