name: tekartik_pubtest

version: 0.7.1
publish_to: none
environment:
  sdk: ^3.7.0
dependencies:
  args: ">=2.6.0"
  path: ">=1.9.0"
  pool: ">=1.5.1"
  pub_semver: ">=2.1.4"
  process_run: ">=1.2.1+1"
  synchronized:
  yaml: ">=3.1.2"
  tekartik_pub:
    git:
      url: https://github.com/tekartik/pub.dart
      ref: dart3a
    version: '>=0.11.0'
  tekartik_sc:
    git:
      url: https://github.com/tekartik/sc.dart
      ref: dart3a
    version: '>=0.9.0'
  tekartik_io_utils:
    git:
      url: https://github.com/tekartik/io_utils.dart
      ref: dart3a
    version: '>=0.5.2'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7+1'
  fs_shim: ">=2.3.3+1"
dev_dependencies:
  dev_build: ">=1.1.2"
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_test: '>=0.10.2'
#test_dependencies: []
dependency_overrides:
#  tekartik_pub:
#    path: ../pub.dart
#  fs_shim:
#    git: https://github.com/tekartik/fs_shim.dart
#  process_run:
#    path: ../process_run.dart
#    git: https://github.com/tekartik/process_run.dart
executables:
  # pubtest:
  pubtestdependencies:
  pubtestpackage:
