name: pubtest
author: Alexandre Roux <alex@tekartik.com>
version: 0.1.0
dependencies:
  args: any
  path: any
  pool: any
  pub_semver: any
  process_run: any
  yaml: any
  tekartik_pub:
    git: git://github.com/tekartik/tekartik_pub.dart
  fs_shim: any
dev_dependencies:
  dev_test: any
  test: any
  fs_shim_test:
    git: git://github.com/tekartik/fs_shim_test.dart
test_dependencies: []
dependency_overrides:
#  tekartik_pub:
#    path: /media/ssd/devx/git/github.com/tekartik/tekartik_pub.dart
#  fs_shim:
#    git: git://github.com/tekartik/fs_shim.dart
#  process_run:
#    git: git://github.com/tekartik/process_run.dart
executables:
  pubtest:
  pubtestdependencies: