name: pubtest
author: Alexandre Roux <alex@tekartik.com>
version: 0.4.1
environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'
dependencies:
  args: any
  path: any
  pool: any
  pub_semver: any
  process_run: '>=0.6.0-dev.1'
  yaml: any
  tekartik_pub:
    git:
      url: git://github.com/tekartik/pub.dart
      ref: dart2
    version: '>=0.7.1'
  tekartik_sc:
    git:
      url: git://github.com/tekartik/sc.dart
      ref: dart2
    version: '>=0.3.1'
  tekartik_io_utils:
    git:
      url: git://github.com/tekartik/io_utils.dart
      ref: dart2
  fs_shim: '>=0.7.3'
dev_dependencies:
  dev_test: '>=0.12.0-dev.1'
  test: '>=1.2.0'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.3'
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
#test_dependencies: []
dependency_overrides:
#  tekartik_pub:
#    path: ../pub.dart
#  fs_shim:
#    git: git://github.com/tekartik/fs_shim.dart
#  process_run:
#    git: git://github.com/tekartik/process_run.dart
executables:
  pubtest:
  pubtestdependencies:
  pubtestpackage: