name: tekartik_pubtest
author: Alexandre Roux <alex@tekartik.com>
version: 0.6.8
environment:
  sdk: '>=2.8.0 <3.0.0'
dependencies:
  args: any
  path: any
  pool: any
  pub_semver: any
  process_run: '>=0.10.9-dev.1'
  yaml: any
  tekartik_pub:
    git:
      url: git://github.com/tekartik/pub.dart
      ref: dart2
    version: '>=0.10.17'
  tekartik_sc:
    git:
      url: git://github.com/tekartik/sc.dart
      ref: dart2
    version: '>=0.8.5+1'
  tekartik_io_utils:
    git:
      url: git://github.com/tekartik/io_utils.dart
      ref: dart2
    version: '>=0.5.2'
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.10.7+1'
  fs_shim: '>=0.7.3'
dev_dependencies:
  dev_test: '>=0.13.2-dev.3'
  test: '>=1.2.0'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.4'
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
#test_dependencies: []
dependency_overrides:
#  tekartik_pub:
#    path: ../pub.dart
#  fs_shim:
#    git: git://github.com/tekartik/fs_shim.dart
#  process_run:
#    git: git://github.com/tekartik/process_run.dart
executables:
  pubtest:
  pubtestdependencies:
  pubtestpackage: