name: pubtest
author: Alexandre Roux <alex@tekartik.com>
version: 0.4.0
dependencies:
  args: any
  path: any
  pool: any
  pub_semver: any
  process_run: '>=0.5.0'
  yaml: any
  tekartik_pub:
    git: git://github.com/tekartik/pub.dart
    version: '>=0.7.1'
  tekartik_sc:
    git: git://github.com/tekartik/sc.dart
    version: '>=0.3.1'
  tekartik_common_utils:
    git: git://github.com/tekartik/common_utils.dart
    version: '>=0.5.1'
  tekartik_io_utils:
    git: git://github.com/tekartik/io_utils.dart
  fs_shim: '>=0.7.3'
dev_dependencies:
  dev_test: any
  test: '>=0.12.24+6'
  fs_shim_test:
    git: git://github.com/tekartik/fs_shim_test.dart
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
    version: '>=0.1.3'
#test_dependencies: []
dependency_overrides:
#  tekartik_pub:
#    path: ../pub.dart
#  fs_shim:
#    git: git://github.com/tekartik/fs_shim.dart
#  process_run:
#    git: git://github.com/tekartik/process_run.dart
executables:
  pubtest:
  pubtestdependencies:
  pubtestpackage: