name: pubtest_example_simple_failed
environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'
dependencies:
  pubtest_example_simple_failed_dependency:
    path: ../simple_failed_dependency
dev_dependencies:
  test: '>=1.2.0'
  dev_test: '>=0.12.0-dev.1'


